### ISSUE TITLE
Could not load 'plugins/UnderscoreEnchants-2.1-beta1.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by jason31416** [RoughlyUnderscore/UnderscoreEnchants#9]
**Describe the bug**
So I am using purpur 1.19.4 with java 17, and I couldn't load this plugin

**Full stacktrace**
[17:31:24] [Server thread/ERROR]: Could not load 'plugins/UnderscoreEnchants-2.1-beta1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/roughlyunderscore/enchs/UnderscoreEnchants has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:158) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:413) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:321) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:436) ~[paper-1.19.3.jar:git-Paper-368]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.3.jar:git-Paper-368]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-368]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-368]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.UnsupportedClassVersionError: com/roughlyunderscore/enchs/UnderscoreEnchants has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:223) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:129) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:154) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	... 7 more

**Screenshots**

**Version**
I am using underscoreEnchants 2.1

Is there anyway to fix this?

**Comment by RoughlyUnderscore** [comment]
Hey, as stated in the documentation, the minimum version required for UnderscoreEnchants to start is Java 19.
![image](https://github.com/RoughlyUnderscore/UnderscoreEnchants/assets/75266403/87ef43a2-ee7f-40fb-943f-70a81952d71a)
Please update your Java to 19 and report back. Do not forget the `--enable-preview` flag:
![image](https://github.com/RoughlyUnderscore/UnderscoreEnchants/assets/75266403/f2718a9a-d2d0-4b1b-a674-a52c65e51781)
